
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CitiesPortType", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CitiesPortType {


    /**
     * 
     * @param name
     * @return
     *     returns mypackage.City
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getByName")
    @WebResult(name = "city", targetNamespace = "")
    @RequestWrapper(localName = "getByName", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetByName")
    @ResponseWrapper(localName = "getByNameResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetByNameResponse")
    public City getByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns mypackage.City
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getCapitalByCountryName")
    @WebResult(name = "city", targetNamespace = "")
    @RequestWrapper(localName = "getCapitalByCountryName", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetCapitalByCountryName")
    @ResponseWrapper(localName = "getCapitalByCountryNameResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetCapitalByCountryNameResponse")
    public City getCapitalByCountryName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param isoCode
     * @return
     *     returns mypackage.City
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getCapitalByISOCode")
    @WebResult(name = "city", targetNamespace = "")
    @RequestWrapper(localName = "getCapitalByISOCode", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetCapitalByISOCode")
    @ResponseWrapper(localName = "getCapitalByISOCodeResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetCapitalByISOCodeResponse")
    public City getCapitalByISOCode(
        @WebParam(name = "iso_code", targetNamespace = "")
        String isoCode);

    /**
     * 
     * @param name
     * @return
     *     returns mypackage.ArrayOfCities
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#searchByName")
    @WebResult(name = "cities", targetNamespace = "")
    @RequestWrapper(localName = "searchByName", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.SearchByNameResponse")
    public ArrayOfCities searchByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns mypackage.ArrayOfCities
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getAll")
    @WebResult(name = "cities", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetAllResponse")
    public ArrayOfCities getAll();

    /**
     * 
     * @param id
     * @return
     *     returns mypackage.City
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getById")
    @WebResult(name = "city", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetByIdResponse")
    public City getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param cityId
     * @return
     *     returns int
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getArea")
    @WebResult(name = "area", targetNamespace = "")
    @RequestWrapper(localName = "getArea", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetArea")
    @ResponseWrapper(localName = "getAreaResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetAreaResponse")
    public int getArea(
        @WebParam(name = "city_id", targetNamespace = "")
        int cityId);

    /**
     * 
     * @param cityId
     * @return
     *     returns int
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/#getPopulation")
    @WebResult(name = "population", targetNamespace = "")
    @RequestWrapper(localName = "getPopulation", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetPopulation")
    @ResponseWrapper(localName = "getPopulationResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/cities/types", className = "mypackage.GetPopulationResponse")
    public int getPopulation(
        @WebParam(name = "city_id", targetNamespace = "")
        int cityId);

}
