
package location;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationsService", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/locations", wsdlLocation = "http://pis.predmety.fiit.stuba.sk/pis/ws/GeoServices/Locations?WSDL")
public class LocationsService
    extends Service
{

    private final static URL LOCATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONSSERVICE_EXCEPTION;
    private final static QName LOCATIONSSERVICE_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/locations", "LocationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pis.predmety.fiit.stuba.sk/pis/ws/GeoServices/Locations?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONSSERVICE_WSDL_LOCATION = url;
        LOCATIONSSERVICE_EXCEPTION = e;
    }

    public LocationsService() {
        super(__getWsdlLocation(), LOCATIONSSERVICE_QNAME);
    }

    public LocationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONSSERVICE_QNAME, features);
    }

    public LocationsService(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONSSERVICE_QNAME);
    }

    public LocationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONSSERVICE_QNAME, features);
    }

    public LocationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationsPortType
     */
    @WebEndpoint(name = "LocationsPort")
    public LocationsPortType getLocationsPort() {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/locations", "LocationsPort"), LocationsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationsPortType
     */
    @WebEndpoint(name = "LocationsPort")
    public LocationsPortType getLocationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/locations", "LocationsPort"), LocationsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONSSERVICE_EXCEPTION!= null) {
            throw LOCATIONSSERVICE_EXCEPTION;
        }
        return LOCATIONSSERVICE_WSDL_LOCATION;
    }

}
