
package mailnotificator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MailService", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/notificationservices/mail", wsdlLocation = "http://pis.predmety.fiit.stuba.sk/pis/ws/NotificationServices/Mail?WSDL")
public class MailService
    extends Service
{

    private final static URL MAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILSERVICE_EXCEPTION;
    private final static QName MAILSERVICE_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/notificationservices/mail", "MailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pis.predmety.fiit.stuba.sk/pis/ws/NotificationServices/Mail?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAILSERVICE_WSDL_LOCATION = url;
        MAILSERVICE_EXCEPTION = e;
    }

    public MailService() {
        super(__getWsdlLocation(), MAILSERVICE_QNAME);
    }

    public MailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILSERVICE_QNAME, features);
    }

    public MailService(URL wsdlLocation) {
        super(wsdlLocation, MAILSERVICE_QNAME);
    }

    public MailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILSERVICE_QNAME, features);
    }

    public MailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MailPortType
     */
    @WebEndpoint(name = "MailPort")
    public MailPortType getMailPort() {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/notificationservices/mail", "MailPort"), MailPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailPortType
     */
    @WebEndpoint(name = "MailPort")
    public MailPortType getMailPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/notificationservices/mail", "MailPort"), MailPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILSERVICE_EXCEPTION!= null) {
            throw MAILSERVICE_EXCEPTION;
        }
        return MAILSERVICE_WSDL_LOCATION;
    }

}
