
package weatherforecast;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherForecastService", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast", wsdlLocation = "http://pis.predmety.fiit.stuba.sk/pis/ws/WeatherForecast?WSDL")
public class WeatherForecastService
    extends Service
{

    private final static URL WEATHERFORECASTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERFORECASTSERVICE_EXCEPTION;
    private final static QName WEATHERFORECASTSERVICE_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/weatherforecast", "WeatherForecastService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pis.predmety.fiit.stuba.sk/pis/ws/WeatherForecast?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERFORECASTSERVICE_WSDL_LOCATION = url;
        WEATHERFORECASTSERVICE_EXCEPTION = e;
    }

    public WeatherForecastService() {
        super(__getWsdlLocation(), WEATHERFORECASTSERVICE_QNAME);
    }

    public WeatherForecastService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERFORECASTSERVICE_QNAME, features);
    }

    public WeatherForecastService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERFORECASTSERVICE_QNAME);
    }

    public WeatherForecastService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERFORECASTSERVICE_QNAME, features);
    }

    public WeatherForecastService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherForecastService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherForecastPortType
     */
    @WebEndpoint(name = "WeatherForecastPort")
    public WeatherForecastPortType getWeatherForecastPort() {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/weatherforecast", "WeatherForecastPort"), WeatherForecastPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForecastPortType
     */
    @WebEndpoint(name = "WeatherForecastPort")
    public WeatherForecastPortType getWeatherForecastPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/weatherforecast", "WeatherForecastPort"), WeatherForecastPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERFORECASTSERVICE_EXCEPTION!= null) {
            throw WEATHERFORECASTSERVICE_EXCEPTION;
        }
        return WEATHERFORECASTSERVICE_WSDL_LOCATION;
    }

}
