
package weatherforecast;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherForecastPortType", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherForecastPortType {


    /**
     * 
     * @param date
     * @param coordLon
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getTemperatureByDate")
    @WebResult(name = "temperature", targetNamespace = "")
    @RequestWrapper(localName = "getTemperatureByDate", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetTemperatureByDate")
    @ResponseWrapper(localName = "getTemperatureByDateResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetTemperatureByDateResponse")
    public double getTemperatureByDate(
        @WebParam(name = "date", targetNamespace = "")
        String date,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param coordLon
     * @param year
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getAverageTemperature")
    @WebResult(name = "average", targetNamespace = "")
    @RequestWrapper(localName = "getAverageTemperature", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageTemperature")
    @ResponseWrapper(localName = "getAverageTemperatureResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageTemperatureResponse")
    public double getAverageTemperature(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param date
     * @param coordLon
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getPrecipitationProbability")
    @WebResult(name = "probability", targetNamespace = "")
    @RequestWrapper(localName = "getPrecipitationProbability", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetPrecipitationProbability")
    @ResponseWrapper(localName = "getPrecipitationProbabilityResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetPrecipitationProbabilityResponse")
    public double getPrecipitationProbability(
        @WebParam(name = "date", targetNamespace = "")
        String date,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param coordLon
     * @param year
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getAveragePrecipitationProbability")
    @WebResult(name = "average", targetNamespace = "")
    @RequestWrapper(localName = "getAveragePrecipitationProbability", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAveragePrecipitationProbability")
    @ResponseWrapper(localName = "getAveragePrecipitationProbabilityResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAveragePrecipitationProbabilityResponse")
    public double getAveragePrecipitationProbability(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param date
     * @param coordLon
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getSnowProbability")
    @WebResult(name = "probability", targetNamespace = "")
    @RequestWrapper(localName = "getSnowProbability", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetSnowProbability")
    @ResponseWrapper(localName = "getSnowProbabilityResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetSnowProbabilityResponse")
    public double getSnowProbability(
        @WebParam(name = "date", targetNamespace = "")
        String date,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param coordLon
     * @param year
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getAverageSnowProbability")
    @WebResult(name = "average", targetNamespace = "")
    @RequestWrapper(localName = "getAverageSnowProbability", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageSnowProbability")
    @ResponseWrapper(localName = "getAverageSnowProbabilityResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageSnowProbabilityResponse")
    public double getAverageSnowProbability(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param date
     * @param coordLon
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getWindStrength")
    @WebResult(name = "wind", targetNamespace = "")
    @RequestWrapper(localName = "getWindStrength", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetWindStrength")
    @ResponseWrapper(localName = "getWindStrengthResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetWindStrengthResponse")
    public double getWindStrength(
        @WebParam(name = "date", targetNamespace = "")
        String date,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

    /**
     * 
     * @param coordLon
     * @param year
     * @param coordLat
     * @return
     *     returns double
     */
    @WebMethod(action = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/#getAverageWindStrength")
    @WebResult(name = "average", targetNamespace = "")
    @RequestWrapper(localName = "getAverageWindStrength", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageWindStrength")
    @ResponseWrapper(localName = "getAverageWindStrengthResponse", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/weatherforecast/types", className = "weatherforecast.GetAverageWindStrengthResponse")
    public double getAverageWindStrength(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "coord_lat", targetNamespace = "")
        double coordLat,
        @WebParam(name = "coord_lon", targetNamespace = "")
        double coordLon);

}
