
package peaks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PeaksService", targetNamespace = "http://pis.predmety.fiit.stuba.sk/pis/geoservices/peaks", wsdlLocation = "http://pis.predmety.fiit.stuba.sk/pis/ws/GeoServices/Peaks?WSDL")
public class PeaksService
    extends Service
{

    private final static URL PEAKSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PEAKSSERVICE_EXCEPTION;
    private final static QName PEAKSSERVICE_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/peaks", "PeaksService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pis.predmety.fiit.stuba.sk/pis/ws/GeoServices/Peaks?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEAKSSERVICE_WSDL_LOCATION = url;
        PEAKSSERVICE_EXCEPTION = e;
    }

    public PeaksService() {
        super(__getWsdlLocation(), PEAKSSERVICE_QNAME);
    }

    public PeaksService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEAKSSERVICE_QNAME, features);
    }

    public PeaksService(URL wsdlLocation) {
        super(wsdlLocation, PEAKSSERVICE_QNAME);
    }

    public PeaksService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEAKSSERVICE_QNAME, features);
    }

    public PeaksService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeaksService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeaksPortType
     */
    @WebEndpoint(name = "PeaksPort")
    public PeaksPortType getPeaksPort() {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/peaks", "PeaksPort"), PeaksPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeaksPortType
     */
    @WebEndpoint(name = "PeaksPort")
    public PeaksPortType getPeaksPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pis.predmety.fiit.stuba.sk/pis/geoservices/peaks", "PeaksPort"), PeaksPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEAKSSERVICE_EXCEPTION!= null) {
            throw PEAKSSERVICE_EXCEPTION;
        }
        return PEAKSSERVICE_WSDL_LOCATION;
    }

}
